pipeline {

  agent {
    node {
      label 'catapult-rest-build-node'
    }
  }

  // using the Timestamper plugin we can add timestamps to the console log
  options {
    timestamps()
  }

  environment {
    DOCKER_REGISTRY = "https://249767383774.dkr.ecr.ap-southeast-1.amazonaws.com"
    CREDENTIAL_ID = "ecr:ap-southeast-1:jenkins-ecr"
    IMAGE = "proximax-catapult-rest"
  }

 stages {
    stage('Build') {
      steps {
        sh """
              # Disable exit on non 0
              set +e
              echo "running yarn_setup.sh"
              ./yarn_setup.sh

              cd rest
              npm run build
              cd ..
          """
      }
      post {
        success {
          echo 'Build Success'
        }
      }
    }

    stage('Unit Test') {
      steps {
       sh """
              cd catapult-sdk
              npm run test
              cd ..
          """
       sh """
             cd rest
             npm run test
             cd ..
          """
      }
    }

    stage('Build and Publish Release Image') {
      when {
        tag "release-*"   // only run these stage in tag release-*
      }
      steps {
        echo 'Build and Publish Image'

        script {
            def newImage = docker.build("${IMAGE}")
            docker.withRegistry("${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                newImage.push("release-jenkins-build-${env.BUILD_NUMBER}") // also push using Jenkins build number
                newImage.push("${env.GIT_TAG_NAME}")
            }
        }
      }
      post {
        success {
            slackSend channel: '#devops',
                color: 'good',
                message: "Branch *${env.GIT_BRANCH}* Tag *${env.GIT_TAG_NAME}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker images *${IMAGE}:release-jenkins-build-${env.BUILD_NUMBER}* and *${IMAGE}:${env.GIT_TAG_NAME}*"
        }
      }
    }

    stage('Build and Publish Develop Image') {
      when {
        branch 'develop'  // only run this stage in the develop branch
      }
      steps {
        echo 'Build and Publish Image'

        script {
            def newImage = docker.build("${IMAGE}")
            docker.withRegistry("${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                newImage.push("develop-jenkins-build-${env.BUILD_NUMBER}") // also push using Jenkins build number
                newImage.push("develop") // update Docker image develop
            }
        }
      }
      post {
        success {
            slackSend channel: '#devops',
                color: 'good',
                message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker images *${IMAGE}:develop-jenkins-build-${env.BUILD_NUMBER}* and *${IMAGE}:develop*"
        }
      }
    }
  }

  post {
    failure {
        slackSend channel: '#devops',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}